name: terraform-plan
on:
  push:
    branches:
      - "*"
  workflow_dispatch:
jobs:
  plan:
    uses: "./.github/workflows/template-terraform.yml"
    with:
      command: "plan"
    secrets:
      ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}
      TF_VAR_vsphere_password: ${{ secrets.HL_ESXI_PASSWORD }}
      HL_TF_PRIVATE_KEY: ${{ secrets.HL_TF_PRIVATE_KEY }}
      HL_TF_PRESHARED_KEY: ${{ secrets.HL_TF_PRESHARED_KEY }}
      HL_ENDPOINT: ${{ secrets.HL_ENDPOINT }}